services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cms_db
      MYSQL_USER: cms_user
      MYSQL_PASSWORD: cms_pass
    ports:
      - "3306:3306"
    networks:
      - cms-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      timeout: 5s

  cms-api:
    build: .
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - cms-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/cms_db
      SPRING_DATASOURCE_USERNAME: cms_user
      SPRING_DATASOURCE_PASSWORD: cms_pass
    ports:
      - "8080:8080"

networks:
  cms-network:
    driver: bridge
